name: Workflow Commands
on: push

jobs:
    testing-ef-commands:
        runs-on: ubuntu-latest
        steps:
            - name: Setting an error meassge
              run: echo "::error::Missing semicolon"
            - name: Setting an error meassge with params
              run: echo "::error title=Error title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing Semicolon"
            - name: Setting a debug meassge with params
              run: echo "::debug title=Debug title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing Semicolon"
            - name: Setting an warning meassge with params
              run: echo "::warning title=Warning title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing Semicolon"
            - name: Setting an notice meassge with params
              run: echo "::notice title=Notice title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing Semicolon"
            